//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPYXWS.TPWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TPWS.MsgSendSoap")]
    public interface MsgSendSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMsgExt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendMsgExt(string userCode, string userPass, string DesNo, string Msg, string Channel, string ExeNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMsg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendMsg(string userCode, string userPass, string DesNo, string Msg, string Channel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendVoiceCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendVoiceCode(string userCode, string userPass, string DesNo, string VoiceCode, string Channel, string Amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBalance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetBalance(string userCode, string userPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMoExt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetMoExt(string userCode, string userPass, string minId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMo2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetMo2(string userCode, string userPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetMo(string userCode, string userPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReport2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetReport2(string userCode, string userPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetReport(string userCode, string userPass, string batchNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MsgSendSoapChannel : TPYXWS.TPWS.MsgSendSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MsgSendSoapClient : System.ServiceModel.ClientBase<TPYXWS.TPWS.MsgSendSoap>, TPYXWS.TPWS.MsgSendSoap {
        
        public MsgSendSoapClient() {
        }
        
        public MsgSendSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MsgSendSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MsgSendSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MsgSendSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SendMsgExt(string userCode, string userPass, string DesNo, string Msg, string Channel, string ExeNo) {
            return base.Channel.SendMsgExt(userCode, userPass, DesNo, Msg, Channel, ExeNo);
        }
        
        public string SendMsg(string userCode, string userPass, string DesNo, string Msg, string Channel) {
            return base.Channel.SendMsg(userCode, userPass, DesNo, Msg, Channel);
        }
        
        public string SendVoiceCode(string userCode, string userPass, string DesNo, string VoiceCode, string Channel, string Amount) {
            return base.Channel.SendVoiceCode(userCode, userPass, DesNo, VoiceCode, Channel, Amount);
        }
        
        public string GetBalance(string userCode, string userPass) {
            return base.Channel.GetBalance(userCode, userPass);
        }
        
        public string GetMoExt(string userCode, string userPass, string minId) {
            return base.Channel.GetMoExt(userCode, userPass, minId);
        }
        
        public string GetMo2(string userCode, string userPass) {
            return base.Channel.GetMo2(userCode, userPass);
        }
        
        public string GetMo(string userCode, string userPass) {
            return base.Channel.GetMo(userCode, userPass);
        }
        
        public string GetReport2(string userCode, string userPass) {
            return base.Channel.GetReport2(userCode, userPass);
        }
        
        public string GetReport(string userCode, string userPass, string batchNumber) {
            return base.Channel.GetReport(userCode, userPass, batchNumber);
        }
    }
}
